# $ docker-compose up -d
# Dump do banco de dados:
# $ docker exec mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > all-mysql.sql

version: "3.7"

volumes: 
    db-data:

networks: 
    backend:

services: 
    db:
        image: mysql:8.0
        container_name: mysql
        volumes: 
            - db-data:/var/lib/mysql
            - /d/Projects/Docker/phpmyadmin/mysql/custom:/etc/mysql/conf.d
        environment: 
            - MYSQL_ROOT_PASSWORD=pass
            # Timezone entre host e container
            - TZ=America/Sao_Paulo
        networks: 
            - backend
        restart: always

    myadmin:
        image: phpmyadmin/phpmyadmin:5.0
        container_name: myadmin
        environment: 
            - PMA_HOST=db
            # Timezone entre host e container
            - TZ=America/Sao_Paulo
        ports: 
            - 8080:80
        networks: 
            - backend
        restart: always
        depends_on: 
            - db

    wordpress:
        image: wordpress:5.5.1-php7.4
        container_name: wordpress
        volumes: 
            - /d/Projects/Docker/compose/phpmyadmin/wordpress/conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - /d/Projects/Docker/compose/phpmyadmin/wordpress/html:/var/www/html
        networks: 
            - backend
        environment: 
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=pass
            # Timezone entre host e container
            - TZ=America/Sao_Paulo
        ports: 
            - 9090:80
        restart: always
        depends_on: 
            - db
