version: "3"

networks: 
    net-backend:

services:
    mysql:
        container_name: mysql
        image: mysql:5.5
        volumes: 
            - /d/Projects/Docker/compose/owncloud/home/data:/var/lib/mysql
            #- /d/Projects/Docker/compose/owncloud/etc/localtime:/etc/localtime:ro
        networks: 
            - net-backend
        environment: 
            MYSQL_ROOT_PASSWORD: pass
        restart: always

    owncloud:
        container_name: owncloud
        image: owncloud
        volumes: 
            - /d/Projects/Docker/compose/owncloud/home/apps:/var/www/html/apps
            - /d/Projects/Docker/compose/owncloud/home/config:/var/www/html/config
            - /d/Projects/Docker/compose/owncloud/home/data:/var/www/html/data
            #- /d/Projects/Docker/compose/owncloud/etc/localtime:/etc/localtime:ro
        networks: 
            - net-backend
        ports: 
            - 9090:80
        restart: always
