// <auto-generated />
using ApiNetCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiNetCore.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20200914143556_InitialConfiguration")]
    partial class InitialConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiNetCore.Models.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CatalogBrand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "CatalogBrand"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Azure"
                        },
                        new
                        {
                            Id = 3,
                            Brand = ".NET"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Visual Studio"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "SQL Server"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Other"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "CatalogBrandTestOne"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "CatalogBrandTestTwo"
                        });
                });

            modelBuilder.Entity("ApiNetCore.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<int>("CatalogBrandId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MaxStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("OnReorder")
                        .HasColumnType("bit");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RestockThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogBrandId");

                    b.HasIndex("CatalogTypeId");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 100,
                            CatalogBrandId = 3,
                            CatalogTypeId = 3,
                            Description = ".NET Bot Black Hoodie, and more",
                            MaxStockThreshold = 0,
                            Name = ".NET Bot Black Hoodie",
                            OnReorder = false,
                            PictureFileName = "1.png",
                            Price = 19.5m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 89,
                            CatalogBrandId = 3,
                            CatalogTypeId = 2,
                            Description = ".NET Black & White Mug",
                            MaxStockThreshold = 0,
                            Name = ".NET Black & White Mug",
                            OnReorder = true,
                            PictureFileName = "2.png",
                            Price = 8.50m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 56,
                            CatalogBrandId = 6,
                            CatalogTypeId = 3,
                            Description = "Prism White T-Shirt",
                            MaxStockThreshold = 0,
                            Name = "Prism White T-Shirt",
                            OnReorder = false,
                            PictureFileName = "3.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 120,
                            CatalogBrandId = 3,
                            CatalogTypeId = 3,
                            Description = ".NET Foundation T-shirt",
                            MaxStockThreshold = 0,
                            Name = ".NET Foundation T-shirt",
                            OnReorder = false,
                            PictureFileName = "4.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 55,
                            CatalogBrandId = 6,
                            CatalogTypeId = 4,
                            Description = "Roslyn Red Sheet",
                            MaxStockThreshold = 0,
                            Name = "Roslyn Red Sheet",
                            OnReorder = false,
                            PictureFileName = "5.png",
                            Price = 8.5m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 17,
                            CatalogBrandId = 3,
                            CatalogTypeId = 3,
                            Description = ".NET Blue Hoodie",
                            MaxStockThreshold = 0,
                            Name = ".NET Blue Hoodie",
                            OnReorder = false,
                            PictureFileName = "6.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 8,
                            CatalogBrandId = 6,
                            CatalogTypeId = 3,
                            Description = "Roslyn Red T-Shirt",
                            MaxStockThreshold = 0,
                            Name = "Roslyn Red T-Shirt",
                            OnReorder = false,
                            PictureFileName = "7.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 34,
                            CatalogBrandId = 6,
                            CatalogTypeId = 3,
                            Description = "Kudu Purple Hoodie",
                            MaxStockThreshold = 0,
                            Name = "Kudu Purple Hoodie",
                            OnReorder = false,
                            PictureFileName = "8.png",
                            Price = 8.5m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 76,
                            CatalogBrandId = 6,
                            CatalogTypeId = 2,
                            Description = "Cup<T> White Mug",
                            MaxStockThreshold = 0,
                            Name = "Cup<T> White Mug",
                            OnReorder = false,
                            PictureFileName = "9.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 10,
                            AvailableStock = 11,
                            CatalogBrandId = 3,
                            CatalogTypeId = 4,
                            Description = ".NET Foundation Sheet",
                            MaxStockThreshold = 0,
                            Name = ".NET Foundation Sheet",
                            OnReorder = false,
                            PictureFileName = "10.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 11,
                            AvailableStock = 3,
                            CatalogBrandId = 3,
                            CatalogTypeId = 4,
                            Description = "Cup<T> Sheet",
                            MaxStockThreshold = 0,
                            Name = "Cup<T> Sheet",
                            OnReorder = false,
                            PictureFileName = "11.png",
                            Price = 8.5m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 12,
                            AvailableStock = 0,
                            CatalogBrandId = 6,
                            CatalogTypeId = 3,
                            Description = "Prism White TShirt",
                            MaxStockThreshold = 0,
                            Name = "Prism White TShirt",
                            OnReorder = false,
                            PictureFileName = "12.png",
                            Price = 12m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 13,
                            AvailableStock = 0,
                            CatalogBrandId = 6,
                            CatalogTypeId = 2,
                            Description = "De los Palotes",
                            MaxStockThreshold = 0,
                            Name = "pepito",
                            OnReorder = false,
                            PictureFileName = "13.png",
                            Price = 12m,
                            RestockThreshold = 0
                        });
                });

            modelBuilder.Entity("ApiNetCore.Models.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CatalogType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "CatalogType"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Mug"
                        },
                        new
                        {
                            Id = 3,
                            Type = "T-Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Sheet"
                        },
                        new
                        {
                            Id = 5,
                            Type = "USB Memory Stick"
                        },
                        new
                        {
                            Id = 6,
                            Type = "CatalogTypeTestOne"
                        },
                        new
                        {
                            Id = 7,
                            Type = "CatalogTypeTestTwo"
                        });
                });

            modelBuilder.Entity("ApiNetCore.Models.CatalogItem", b =>
                {
                    b.HasOne("ApiNetCore.Models.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNetCore.Models.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
