# $ docker image build -t my-image . -f Dockerfile.figlet2
# $ docker container run my-image salut

FROM ubuntu
RUN apt-get update
RUN apt-get install figlet -y
# Define um "comando base" (e seus parâmetros) para o container
ENTRYPOINT [ "figlet", "-f", "script" ]
