# $ docker-compose up -d
# Dump do banco de dados:
# $ docker exec mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > all-mysql.sql

version: "3.7"

volumes: 
    db-data:

networks: 
    backend:

services: 
    db:
        image: mysql:8.0
        container_name: mysql
        volumes: 
            - db-data:/var/lib/mysql
            - /d/Projects/Docker/phpmyadmin/mysql/custom:/etc/mysql/conf.d
        environment: 
            - MYSQL_ROOT_PASSWORD=pass
        networks: 
            - backend
        restart: always

    myadmin:
        image: phpmyadmin/phpmyadmin:5.0
        container_name: myadmin
        environment: 
            - PMA_HOST=db
        ports: 
            - 8080:80
        networks: 
            - backend
        restart: always
        depends_on: 
            - db
