version: "3"

networks: 
    back-end:

services: 
    web1:
        container_name: web1
        build: 
            context: .
            dockerfile: Dockerfile.web1
        networks: 
            - back-end

    web2:
        container_name: web2
        build: 
            context: .
            dockerfile: Dockerfile.web2
        networks: 
            - back-end

    loadbalancer:
        container_name: loadbalancer
        build: 
            context: .
            dockerfile: Dockerfile.loadbalancer
        networks: 
            - back-end
        ports: 
            - 5050:80
        depends_on: 
            - web1
            - web2
