# Criar a migracao inicial:
# $ dotnet-ef migrations add InitialConfiguration -o Infrastructure/Migrations --project ApiNetCore.csproj --startup-project ApiNetCore.csproj

# Executar o compose:
# $ docker-compose up -d

# Acessar http://192.168.99.100:3000/api/v1/catalog/items

version: '3.4'

networks:
  back-end:

services:
  webapi:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - back-end
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: mysql
    image: mysql
    networks:
      - back-end
