# $ docker-compose up -d
# $ docker exec -it sql1 bash
# $ /opt/mssql-tools/bin/sqlcmd -U SA -P s-eplh8co6-#_i3Revl+
# /$ CREATE DATABASE TestDB
# /$ SELECT Name from sys.Databases
# /$ GO
# /$ USE TestDB
# /$ CREATE TABLE Inventory (id INT, name NVARCHAR(50), quantity INT)
# /$ INSERT INTO Inventory VALUES (1, 'banana', 150); INSERT INTO Inventory VALUES (2, 'orange', 154);
# /$ GO
# /$ SELECT * FROM Inventory WHERE quantity > 152;
# /$ GO
# /$ QUIT

version: "3.4"

volumes: 
    MsSqlData:

services: 
    sqlserver:
        container_name: sql1
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - 1433:1433
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=s-eplh8co6-#_i3Revl+
            - MSSQL_PID=Developer
        